apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/wizbit/k8s-preview-app-manifest.git'
    targetRevision: HEAD
    path: overlays/production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        istio.io/dataplane-mode: ambient
  destination:
    name: cluster1
    namespace: test-app-production
