apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
#patches:
#  - path: ingress-patch.yaml
images:
  - name: app-image
    newName: marcusspeight/preview-app
    newTag: main
